{% set name = "streamai" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamai-{{ version }}.tar.gz
  sha256: bccd05b00d0e9aad9497be6497a686b6e544d4aaf76810f26d7762794c616a36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fastapi
    - uvicorn
    - fire

test:
  imports:
    - streamai
  commands:
    - pip check
  requires:
    - pip

about:
  summary: finetune latest open source llms in less than 10 line of code.
  license: MIT
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Client request
  recipe-maintainers:
    - ianaobi
